export type MenuItem = {
  id: string
  name: string
  description: string
  ingredients: string
  allergens: string
  price: string
  imageUrl?: string
  badge?: string
  badgeType?: 'gold' | 'green' | 'red' | 'default'
}

export type MenuSubsection = {
  id: string
  label: string
  items: MenuItem[]
}

export type MenuCategory = {
  id: string
  slug: string
  label: string
  shortLabel: string
  eyebrow: string
  description: string
  imageUrl: string
  items: MenuItem[]
  subsections?: MenuSubsection[]
}

export const menuCategories: MenuCategory[] = [
  /* ─────────────────────────────────────────────────── FRÜHSTÜCK */
  {
    id: 'fruehstueck',
    slug: 'fruehstueck',
    label: 'Frühstück & Brunch',
    shortLabel: 'Frühstück',
    eyebrow: 'Ab 10:00 Uhr',
    description: 'Starten Sie entspannt in den Tag — mit frisch gebackenem Brot, sorgfältig ausgewählten Zutaten und dem Duft von Kaffee.',
    imageUrl: '/images/fruehstueck.jpg',
    items: [
      {
        id: 'klassisches-fruehstueck',
        name: 'Klassisches Frühstück',
        description: 'Das perfekte Start-in-den-Tag-Frühstück mit allem was dazu gehört.',
        ingredients: 'Frisches Brot¹, Weißkäse⁷, Frischkäse⁷, Oliven, Tomaten, Gurken, Paprika, gekochtes Ei³, kleine Portion Honig.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '8,90 €',
      },
      {
        id: 'luna-sosis-fruehstueck',
        name: 'Luna Sosis Frühstück',
        description: 'Unser Haus-Favorit — mit knusprig gebratenen Würstchen und allem Drum und Dran.',
        ingredients: 'Frisches Brot¹, Sosis (gebratene Würstchen), Weißkäse⁷, Frischkäse⁷, Oliven, Tomaten, Gurken, Paprika, Spiegelei³ oder Rührei³, kleine Portion Honig.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '9,10 €',
        badge: 'Signature',
        badgeType: 'gold',
      },
      {
        id: 'feinschmecker-fruehstueck',
        name: 'Feinschmecker-Frühstück',
        description: 'Für echte Genießer — mit würzigem Sucuk und doppeltem Ei.',
        ingredients: 'Frisches Brot¹, Sucuk, Frischkäse⁷, Tomaten, Gurken, schwarze Oliven, Honig, Marmelade, zwei Spiegeleier³ oder Rühreier³.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '9,90 €',
      },
      {
        id: 'eier-fruehstueck',
        name: 'Eierfrühstück',
        description: 'Rührei oder Spiegelei, Bacon, Tomate — ein klassisches Frühstück nach Wahl.',
        ingredients: 'Wahlweise Rührei³ oder 2 Spiegeleier³, knuspriger Bacon, frische Tomatenscheiben, Brötchen¹ oder Toast¹. Extras: mit Avocado (+1,50 €) · mit Bacon (+1,00 €).',
        allergens: '¹ Gluten · ³ Eier',
        price: '6,20 €',
      },
      {
        id: 'goldener-morgen',
        name: 'Goldener Morgen',
        description: 'Ein warmes Sandwich mit geschmolzenem Käse, Ei und dänischer Remoulade.',
        ingredients: 'Sandwich¹, geschmolzener Käse⁷, Spiegelei³, Dänische Remoulade³, Toastbrot¹, Schinken.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '5,45 €',
      },
      {
        id: 'fruehstuecksfreude',
        name: 'Frühstücksfreude',
        description: 'Eine bunte Auswahl mit Schafskäse, Mortadella und eingelegten Peperoni.',
        ingredients: 'Schafskäse, Käsescheibe⁷, Mortadella⁷, gekochte Eier³, Oliven, Tomaten, Gurken, eingelegte Peperoni.',
        allergens: '³ Eier · ⁷ Milch/Laktose',
        price: '8,90 €',
      },
      {
        id: 'sunny-twins',
        name: 'Sunny Twins',
        description: 'Ein besonderer Teller — karamellisierte Zwiebeln, Pinienkerne und ein Hauch Granatapfelsirup.',
        ingredients: 'Gurken, Tomaten, Eier³, karamellisierte Zwiebeln, Pinienkerne, Granatapfelsirup.',
        allergens: '³ Eier · Pinienkerne (Schalenfrüchte)',
        price: '7,95 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
      {
        id: 'sucuk-ei',
        name: 'Sucuk & Ei',
        description: 'Zwei Spiegeleier mit würzigem Sucuk — klassisch und sättigend.',
        ingredients: 'Zwei Spiegeleier³, Sucuk, Tomaten, Gurken, schwarze Oliven, frisches Brot¹.',
        allergens: '¹ Gluten · ³ Eier',
        price: '9,10 €',
      },
      {
        id: 'lachs-frischkaese-bagel',
        name: 'Lachs & Frischkäse Bagel',
        description: 'Geräucherter Lachs auf cremigem Frischkäse mit Rucola und Zitrone.',
        ingredients: 'Sesam-Bagel¹, Frischkäse⁷, geräucherter Lachs⁴, Gurkenscheiben, Rucola, Zitrone.',
        allergens: '¹ Gluten · ⁴ Fisch · ⁷ Milch/Laktose · Sesam',
        price: '6,45 €',
      },
      {
        id: 'luz-de-luna-bagel',
        name: 'Luz de Luna Bagel',
        description: 'Unser Haus-Bagel — Sucuk, geschmolzener Käse und Rucola.',
        ingredients: 'Sesam-Bagel¹, gebratene Sucuk-Scheiben, Frischkäse⁷, geschmolzener Käse³, Tomatenscheiben, Rucola.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose · Sesam',
        price: '6,20 €',
        badge: 'Signature',
        badgeType: 'gold',
      },
      {
        id: 'spiegelei-avocado-bagel',
        name: 'Spiegelei & Avocado Bagel',
        description: 'Cremige Avocado, Spiegelei und ein Hauch Chiliflocken.',
        ingredients: 'Sesam-Bagel¹, Spiegelei³, Avocadoscheiben, Rucola, Frischkäse⁷, Chiliflocken.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose · Sesam',
        price: '5,50 €',
        badge: 'Vegetarisch',
        badgeType: 'green',
      },
      {
        id: 'daily-power-plate',
        name: 'Daily Power Plate',
        description: 'Unser größtes Frühstück — Bagel, Gemüse, Ei, Früchte und Sosis in einer Portion.',
        ingredients: 'Sesam-Bagel¹ mit Frischkäse, Paprika, Avocado, gebratene Pilze, Rührei³, Gurken, große gebratene Sosis, Blaubeeren, Erdbeeren, frische Orangenspalte.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose · Sesam',
        price: '10,45 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
      {
        id: 'sunny-side-strong',
        name: 'Sunny Side Strong',
        description: 'Omelette mit Füllung nach Wahl, Rucola, Oliven und Tomaten.',
        ingredients: 'Omelette³ mit Füllung nach Wahl, Rucola, Oliven, Tomaten, Gurken. Extras: Hirtenkäse (+0,70 €) · Spinat (+0,50 €) · Mozzarella (+0,50 €) · Wurst (+0,90 €).',
        allergens: '³ Eier · ⁷ Milch/Laktose (je nach Füllung)',
        price: '7,95 €',
      },
      {
        id: 'pesto-rosso-stulle',
        name: 'Pesto Rosso Stulle',
        description: 'Pesto, Mozzarella, Tomaten (frisch & getrocknet), Rucola und Basilikum.',
        ingredients: 'Pesto Rosso, Mozzarella⁷, frische Tomaten, getrocknete Tomaten, Rucola, Basilikum, Olivenöl.',
        allergens: '¹ Gluten · ⁷ Milch/Laktose · Pinienkerne (Schalenfrüchte)',
        price: '7,75 €',
        badge: 'Vegetarisch',
        badgeType: 'green',
      },
      {
        id: 'caprese-toast',
        name: 'Caprese-Toast',
        description: 'Mozzarella, frische Tomaten und ein Schuss Balsamico — einfach, köstlich.',
        ingredients: 'Toast¹, Mozzarella⁷, frische Tomatenscheiben, Balsamico-Creme.',
        allergens: '¹ Gluten · ⁷ Milch/Laktose',
        price: '4,95 €',
        badge: 'Vegetarisch',
        badgeType: 'green',
      },
      {
        id: 'avocado-ei-toast',
        name: 'Avocado & Ei Toast',
        description: 'Spiegelei, cremige Avocado und Chiliflocken auf Toast.',
        ingredients: 'Toast¹, Spiegelei³, Avocado, Zitronendressing, Chiliflocken.',
        allergens: '¹ Gluten · ³ Eier',
        price: '4,45 €',
        badge: 'Vegetarisch',
        badgeType: 'green',
      },
      {
        id: 'lachs-avocado-toast',
        name: 'Lachs-Avocado-Toast',
        description: 'Geräucherter Lachs, Avocado und Honig-Senf auf Toast.',
        ingredients: 'Toast¹, frische Avocado, geräucherter Lachs⁴, Honig-Senf, Zitronensaft.',
        allergens: '¹ Gluten · ⁴ Fisch · Senf',
        price: '5,50 €',
      },
      {
        id: 'croissant-klassiker',
        name: 'Croissant-Klassiker',
        description: 'Buttercroissant mit Butter und Marmelade — der zeitlose Klassiker.',
        ingredients: 'Buttercroissant¹³, Butter³⁷, Marmeladen.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '3,10 €',
      },
      {
        id: 'croissant-suesse-verfuehrung',
        name: 'Croissant „Süße Verführung"',
        description: 'Nutella, frische Erdbeeren und Puderzucker.',
        ingredients: 'Buttercroissant¹³, Nutella (Haselnüsse, Kakao), frische Erdbeeren, Puderzucker.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose · Haselnüsse',
        price: '4,45 €',
      },
      {
        id: 'croissant-morgenlicht',
        name: 'Croissant „Herzhaftes Morgenlicht"',
        description: 'Rührei, Speck und Cheddar — herzhaft und sättigend.',
        ingredients: 'Buttercroissant¹³, Rührei³, Speck, Cheddar-Käse⁷.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '5,90 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
      {
        id: 'pistazien-croissant',
        name: 'Pistazien-Croissant',
        description: 'Gefüllt mit zarter, hausgemachter Pistaziencreme.',
        ingredients: 'Buttercroissant¹³, Pistaziencreme (Pistazien, Butter⁷, Zucker).',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose · Pistazien',
        price: '4,90 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
      {
        id: 'pancake-schoko-banane',
        name: 'Pancake Schoko Banane',
        description: 'Fluffige Pancakes mit Bananen, Schokosauce und Blaubeeren.',
        ingredients: 'Pancakes¹³, Bananen, Schokosauce, Blaubeeren.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '5,75 €',
      },
      {
        id: 'pancake-classic',
        name: 'Pancake Classic',
        description: 'Klassische Buttermilch-Pancakes mit Ahornsirup.',
        ingredients: 'Pancakes¹³, Ahornsirup.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '4,95 €',
      },
      {
        id: 'pancake-speziell',
        name: 'Pancake Speziell',
        description: 'Mit Erdbeeren, Erdbeersauce und einer Kugel Eis.',
        ingredients: 'Pancakes¹³, frische Erdbeeren, Erdbeersauce, Vanilleeis³⁷.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '5,95 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
    ],
  },

  /* ─────────────────────────────────────────────── MITTAG & ABEND */
  {
    id: 'mittag-abend',
    slug: 'mittag-abend',
    label: 'Mittag & Abend',
    shortLabel: 'Mittag & Abend',
    eyebrow: 'Ab 12:00 Uhr',
    description: 'Herzhafte Gerichte aus aller Welt — von der saftigen Bowl bis zum handgemachten Kibbeh.',
    imageUrl: '/images/mittag.jpg',
    items: [
      {
        id: 'currywurst-klassiker',
        name: 'Currywurst Klassiker',
        description: 'Hausgemachte Currysauce, Pommes und Mayonnaise — ein Hannoveraner Liebling.',
        ingredients: 'Currywurst, hausgemachte Currysauce², Pommes frites, Mayonnaise³.',
        allergens: '² Sellerie · ³ Eier · Senf',
        price: '9,50 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
      {
        id: 'currywurst-nordisch',
        name: 'Currywurst Nordischer Style',
        description: 'Mit Röstzwiebeln, Gewürzgurken und Remoulade — der Norden lässt grüßen.',
        ingredients: 'Currywurst, Röstzwiebeln, Gewürzgurken, Remoulade³, Pommes frites, Mayonnaise³.',
        allergens: '³ Eier · Senf',
        price: '10,50 €',
      },
      {
        id: 'lachs-bowl',
        name: 'Lachs Bowl',
        description: 'Frischer Lachs, Avocado, Edamame und cremiges Sesam-Dressing.',
        ingredients: 'Lachs⁴, Reis, Avocado, Sesam¹, Paprika, Gurken, Edamame, Cherry-Tomaten, Sesam-Dressing¹, Teriyaki.',
        allergens: '¹ Gluten · ⁴ Fisch · Sesam · Soja',
        price: '14,20 €',
        badge: 'Signature',
        badgeType: 'gold',
      },
      {
        id: 'chicken-bowl',
        name: 'Chicken Bowl',
        description: 'Gegrilltes Hähnchen mit Reis, Granatapfel und Teriyaki.',
        ingredients: 'Gegrilltes Hähnchen, Reis, buntes Gemüse, Granatapfel, Sesam-Dressing¹, Teriyaki.',
        allergens: '¹ Gluten · Sesam · Soja',
        price: '12,95 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
      {
        id: 'vegetarische-bowl',
        name: 'Vegetarische Bowl „Hausart"',
        description: 'Hummus, gegrilltes Gemüse, Sprossen und Teriyaki.',
        ingredients: 'Hummus, gegrilltes Gemüse (Zucchini, Pilze, Brokkoli), Sprossen, Teriyaki, Sesam-Dressing.',
        allergens: 'Sesam · Soja',
        price: '11,90 €',
        badge: 'Vegetarisch',
        badgeType: 'green',
      },
      {
        id: 'falafel-bowl',
        name: 'Falafel Bowl',
        description: 'Knusprige Falafel auf Hummus, Reis und Granatapfel.',
        ingredients: 'Falafel, Hummus, Reis¹, Rucola, Granatapfel, Sesam-Dressing¹, Teriyaki.',
        allergens: '¹ Gluten · Sesam · Soja',
        price: '10,90 €',
        badge: 'Vegan',
        badgeType: 'green',
      },
      {
        id: 'rinderteller',
        name: 'Herzhafter Rinderteller',
        description: 'Zarte Rindfleischstreifen auf Butterreis mit Fadennudeln.',
        ingredients: 'Rindfleischstreifen, Butterreis⁷, Fadennudeln¹, Dip.',
        allergens: '¹ Gluten · ⁷ Milch/Laktose',
        price: '15,20 €',
      },
      {
        id: 'rindersteak-hausart',
        name: 'Rindersteak nach Hausart',
        description: 'Saftiges Hacksteak in Paprika-Tomaten-Sahnesoße mit Reis.',
        ingredients: 'Hacksteak, Paprika-Tomaten-Sahnesoße², Reis mit Fadennudeln¹, Dip.',
        allergens: '¹ Gluten · ² Sellerie · ⁷ Milch/Laktose',
        price: '13,50 €',
      },
      {
        id: 'pasta-haehnchen-hollandaise',
        name: 'Pasta Hähnchen & Hollandaise',
        description: 'Hähnchen, Champignons und Sauce Hollandaise auf Pasta.',
        ingredients: 'Hähnchen, Champignons, Sauce Hollandaise³⁷, Pasta¹.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '10,50 €',
      },
      {
        id: 'spaghetti-garnelen',
        name: 'Spaghetti & Garnelen',
        description: 'Cremig-pikante Soße mit Garnelen und frischem Brot.',
        ingredients: 'Spaghetti¹, Garnelen, cremig-pikante Soße, frisches Brot¹.',
        allergens: '¹ Gluten · Krebstiere',
        price: '12,90 €',
      },
      {
        id: 'pasta-pesto-verde',
        name: 'Pasta Pesto Verde',
        description: 'Spaghetti mit Basilikum-Pesto, Pinienkernen und frischen Tomaten.',
        ingredients: 'Spaghetti¹, Basilikum-Pesto (Basilikum, Pinienkerne, Parmesan⁷, Olivenöl), frische Tomaten.',
        allergens: '¹ Gluten · ⁷ Milch/Laktose · Pinienkerne',
        price: '9,90 €',
        badge: 'Vegetarisch',
        badgeType: 'green',
      },
      {
        id: 'cheesy-burrito',
        name: 'Cheesy Burrito Combo',
        description: 'Rinderhack, Käse, Bohnen und Potatoes in Haussoße.',
        ingredients: 'Rinderhack, Käse⁷, Bohnen, Potatoes, Haussoße.',
        allergens: '¹ Gluten · ⁷ Milch/Laktose',
        price: '10,90 €',
      },
      {
        id: 'tacos-de-la-casa',
        name: 'Tacos de la Casa',
        description: 'Rinderhack, frisches Gemüse, Limette und Haussoße.',
        ingredients: 'Rinderhack, frisches Gemüse, Limette, Haussoße.',
        allergens: '¹ Gluten',
        price: '8,50 €',
      },
      {
        id: 'genuss-rolle-haehnchen',
        name: 'Genuss-Rolle Hähnchen',
        description: 'Hähnchen mit Spezialsoße und Pommes frites.',
        ingredients: 'Hähnchen, Spezialsoße, Pommes frites.',
        allergens: '¹ Gluten · ³ Eier (Soße)',
        price: '9,90 €',
      },
      {
        id: 'genuss-rolle-falafel',
        name: 'Genuss-Rolle Falafel',
        description: 'Knusprige Falafel mit Spezialsoße und Pommes frites.',
        ingredients: 'Falafel, Spezialsoße, Pommes frites.',
        allergens: '¹ Gluten · Sesam',
        price: '9,50 €',
        badge: 'Vegan',
        badgeType: 'green',
      },
      {
        id: 'lunas-lachsliebe',
        name: 'Lunas Lachsliebe',
        description: 'Zarter Lachs in Curry-Soße mit Basmati-Reis und Kräutern.',
        ingredients: 'Lachsfilet⁴, Curry-Soße, Basmati-Reis, Kräuter, Dip.',
        allergens: '⁴ Fisch · ⁷ Milch/Laktose (Soße)',
        price: '14,50 €',
        badge: 'Signature',
        badgeType: 'gold',
      },
      {
        id: 'cheesy-chicken-panini',
        name: 'Cheesy Chicken Panini',
        description: 'Hähnchen, Käse, Zwiebeln und Potatoes im Panini.',
        ingredients: 'Panini¹, Hähnchen, Käse⁷, Zwiebeln, Potatoes.',
        allergens: '¹ Gluten · ⁷ Milch/Laktose',
        price: '9,90 €',
      },
      {
        id: 'orientalische-kibbeh',
        name: 'Orientalische Kibbeh',
        description: 'Hausgemachte Kibbeh mit Rinderhack-Füllung und Salatgarnitur.',
        ingredients: 'Kibbeh¹ (Rinderhack-Füllung, Bulgur, Gewürze), Salatgarnitur, Dip.',
        allergens: '¹ Gluten · Pinienkerne',
        price: '10,50 €',
      },
      {
        id: 'haehnchen-schnitzel-hollandaise',
        name: 'Hähnchen-Schnitzel Hollandaise',
        description: 'Hähnchenschnitzel mit Hollandaise, Brokkoli und Pommes.',
        ingredients: 'Hähnchenschnitzel¹, Sauce Hollandaise³⁷, Brokkoli, Pommes frites.',
        allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
        price: '10,50 €',
      },
      {
        id: 'haehnchen-schnitzel-wiener',
        name: 'Hähnchen-Schnitzel „Wiener Art"',
        description: 'Paniertes Schnitzel mit Pommes, Zitrone und Dip.',
        ingredients: 'Hähnchenschnitzel¹³, Pommes frites, Zitrone, Dip.',
        allergens: '¹ Gluten · ³ Eier',
        price: '9,50 €',
        badge: 'Beliebt',
        badgeType: 'gold',
      },
    ],
  },

  /* ─────────────────────────────────────────────── SNACKS & DRINKS */
  {
    id: 'snacks-drinks',
    slug: 'snacks-drinks',
    label: 'Snacks & Drinks',
    shortLabel: 'Snacks & Drinks',
    eyebrow: 'Täglich',
    description: 'Von knusprigen Snacks und süßen Desserts bis zum perfekten Kaffee und erfrischenden Drinks.',
    imageUrl: '/images/getraenk.jpg',
    items: [],
    subsections: [
      /* ── Snacks & Salate ── */
      {
        id: 'snacks-salate',
        label: 'Snacks & Salate',
        items: [
          {
            id: 'nachos-dips',
            name: 'Nachos mit Dips',
            description: 'Knusprige Nachos mit Dips — oder mit Käse und Jalapeños.',
            ingredients: 'Nachos¹, Dips. Mit Käse⁷ (+1,00 €) · +Jalapeños (+1,00 €).',
            allergens: '¹ Gluten · ⁷ Milch/Laktose (mit Käse)',
            price: 'ab 3,50 €',
          },
          {
            id: 'chicken-nuggets',
            name: 'Chicken Nuggets',
            description: 'Knusprig frittierte Hähnchen-Nuggets.',
            ingredients: 'Hähnchen-Nuggets¹³, Dip.',
            allergens: '¹ Gluten · ³ Eier',
            price: '6,25 €',
          },
          {
            id: 'mozzarella-sticks',
            name: 'Mozzarella Sticks',
            description: 'Panierte Mozzarella-Sticks, außen knusprig, innen schmelzend.',
            ingredients: 'Mozzarella⁷¹, Panade¹³, Dip.',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
            price: '5,00 €',
          },
          {
            id: 'chicken-strips',
            name: 'Chicken Strips',
            description: 'Zarte Hähnchen-Streifen in knuspriger Panade.',
            ingredients: 'Hähnchen-Streifen¹³, Dip. Side Extras: +Pommes (+3,00 €) · +Süßkartoffeln (+4,00 €).',
            allergens: '¹ Gluten · ³ Eier',
            price: '6,40 €',
          },
          {
            id: 'chicken-luna-salat',
            name: 'Chicken „Luna" Salat',
            description: 'Frischer Eisbergsalat mit Chicken-Streifen und Dressing nach Wahl.',
            ingredients: 'Eisberg, Cherrytomaten, Chicken-Streifen, Dressing nach Wahl.',
            allergens: 'Glutenspuren möglich (Dressing)',
            price: '11,00 €',
            badge: 'Beliebt',
            badgeType: 'gold',
          },
          {
            id: 'salat-garnelen',
            name: 'Salat „Garnelen Classico"',
            description: 'Garnelen auf gemischtem Salat mit Avocado und Zitronen-Olivenöl.',
            ingredients: 'Garnelen (Krebstiere), gemischter Salat, Avocado, Zitronen-Olivenöl-Dressing.',
            allergens: 'Krebstiere',
            price: '13,90 €',
          },
          {
            id: 'klassische-pommes',
            name: 'Klassische Pommes',
            description: 'Goldgelbe, knusprige Pommes frites.',
            ingredients: 'Kartoffeln, Pflanzenöl, Salz.',
            allergens: 'Keine bekannten Hauptallergene.',
            price: '4,90 €',
          },
          {
            id: 'suesskartoffel-pommes',
            name: 'Süßkartoffel-Pommes',
            description: 'Süßkartoffel-Pommes mit Dip.',
            ingredients: 'Süßkartoffeln, Pflanzenöl, Gewürze, Dip.',
            allergens: '³ Eier (Dip)',
            price: '5,90 €',
          },
          {
            id: 'chili-cheese-fries',
            name: 'Chili-Cheese Fries',
            description: 'Pommes oder Süßkartoffeln mit Chili-Käse-Soße.',
            ingredients: 'Pommes frites oder Süßkartoffel-Pommes, Chili-Käse-Soße⁷, Jalapeños.',
            allergens: '⁷ Milch/Laktose',
            price: 'Pommes 10,50 € · Süßkartoffel 11,50 €',
          },
        ],
      },

      /* ── Desserts ── */
      {
        id: 'desserts',
        label: 'Desserts',
        items: [
          {
            id: 'lava-cake',
            name: 'Lava Cake',
            description: 'Warmer Schokoladenkuchen mit flüssigem Kern. Mit Vanilleeis (+1,50 €).',
            ingredients: 'Schokolade, Mehl¹, Eier³, Butter⁷, Zucker. Optional: Vanilleeis³⁷.',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
            price: '3,90 €',
            badge: 'Beliebt',
            badgeType: 'gold',
          },
          {
            id: 'san-sebastian-cheesecake',
            name: 'San Sebastian Cheesecake',
            description: 'Cremiger Basken-Cheesecake — leicht karamellisierte Oberfläche, samtig innen.',
            ingredients: 'Frischkäse⁷, Eier³, Sahne⁷, Zucker, Speisestärke.',
            allergens: '³ Eier · ⁷ Milch/Laktose',
            price: '5,80 €',
            badge: 'Signature',
            badgeType: 'gold',
          },
          {
            id: 'torte-pistazientraum',
            name: 'Pistazientraum-Torte',
            description: 'Feine Pistaziencreme auf lockerem Tortenboden.',
            ingredients: 'Tortenboden¹³⁷, Pistaziencreme (Pistazien, Butter⁷, Zucker).',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose · Pistazien',
            price: '5,50 €',
          },
          {
            id: 'torte-lotus-biscoff',
            name: 'Lotus-Biscoff-Torte',
            description: 'Cremige Torte auf Biscoff-Boden mit karamellisierter Note.',
            ingredients: 'Biscoff-Kekse¹, Frischkäse⁷, Schlagsahne⁷, Biscoff-Aufstrich¹.',
            allergens: '¹ Gluten · ⁷ Milch/Laktose · Soja',
            price: '4,95 €',
          },
          {
            id: 'torte-himbeere-streusel',
            name: 'Himbeere-Streusel-Torte',
            description: 'Frische Himbeeren auf Vanillecreme mit knusprigen Streuseln.',
            ingredients: 'Tortenboden¹³⁷, Vanillecreme⁷, frische Himbeeren, Streusel¹³⁷.',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
            price: '4,50 €',
          },
          {
            id: 'waffel-midnight-berry',
            name: 'Midnight Berry Bliss',
            description: 'Waffel mit Beerenmix, Blaubeersauce und Schlagsahne. (Winter)',
            ingredients: 'Waffel¹³⁷, Beerenmix, Blaubeersauce, Schlagsahne⁷.',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
            price: '6,30 €',
            badge: 'Saisonal',
            badgeType: 'red',
          },
          {
            id: 'waffel-golden-caramel',
            name: 'Golden Caramel Dream',
            description: 'Waffel mit Karamellsauce, Butterscotch und Vanilleeis. (Winter)',
            ingredients: 'Waffel¹³⁷, Karamellsauce, Butterscotch, Vanilleeis³⁷.',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
            price: '6,80 €',
            badge: 'Saisonal',
            badgeType: 'red',
          },
          {
            id: 'waffel-moonlight-classic',
            name: 'Moonlight Classic',
            description: 'Waffel mit Puderzucker und Ahornsirup — schlicht und perfekt. (Winter)',
            ingredients: 'Waffel¹³⁷, Puderzucker, Ahornsirup.',
            allergens: '¹ Gluten · ³ Eier · ⁷ Milch/Laktose',
            price: '5,90 €',
            badge: 'Saisonal',
            badgeType: 'red',
          },
        ],
      },

      /* ── Kaffee & Kalter Kaffee ── */
      {
        id: 'kaffee',
        label: 'Kaffee & Kalter Kaffee',
        items: [
          {
            id: 'espresso',
            name: 'Espresso',
            description: 'Kräftiger Espresso aus hausgemischter Bohne.',
            ingredients: 'Espresso. Kuhmilch⁷ oder Hafermilch¹ auf Wunsch.',
            allergens: '⁷ Milch (je nach Wahl)',
            price: '2,50 €',
          },
          {
            id: 'kaffee-crema',
            name: 'Kaffee Crema',
            description: 'Langer Kaffee mit cremiger Crema.',
            ingredients: 'Espresso, heißes Wasser. Kuhmilch⁷ oder Hafermilch¹ auf Wunsch.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '3,00 €',
          },
          {
            id: 'cappuccino',
            name: 'Cappuccino',
            description: 'Espresso mit aufgeschäumter Milch und Kakao.',
            ingredients: 'Espresso, aufgedämpfte Milch⁷ oder Hafermilch¹, Kakao.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '3,50 €',
          },
          {
            id: 'latte-macchiato',
            name: 'Latte Macchiato',
            description: 'Viel Milchschaum, Espresso — in Schichten serviert.',
            ingredients: 'Espresso, aufgedämpfte Milch⁷ oder Hafermilch¹.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '3,80 €',
          },
          {
            id: 'flat-white',
            name: 'Flat White',
            description: 'Doppelter Ristretto, seidiger Milchschaum.',
            ingredients: 'Doppio Ristretto, aufgedämpfte Milch⁷ oder Hafermilch¹.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '3,80 €',
            badge: 'Beliebt',
            badgeType: 'gold',
          },
          {
            id: 'chai-latte',
            name: 'Chai Latte',
            description: 'Würziger Chai mit Ingwer, Zimt und Kardamom.',
            ingredients: 'Chai-Konzentrat (Ingwer, Zimt, Kardamom, Nelken), Milch⁷ oder Hafermilch¹.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '3,80 €',
          },
          {
            id: 'heisse-schokolade',
            name: 'Heiße Schokolade',
            description: 'Cremige Schokolade mit Milchschaum.',
            ingredients: 'Kakao, Milch⁷ oder Hafermilch¹, Zucker.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '3,50 €',
          },
          {
            id: 'blue-moon-latte',
            name: 'Blue Moon Latte',
            description: 'Unser Signature-Kaffee — Butterfly-Pea-Blüte, Vanille, Milch.',
            ingredients: 'Butterfly-Pea-Tee, Vanillesirup, Milch⁷ oder Hafermilch¹, Espresso.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '4,10 €',
            badge: 'Signature',
            badgeType: 'gold',
          },
          {
            id: 'eiskaffee',
            name: 'Eiskaffee',
            description: 'Espresso mit Vanilleeis und Schlagsahne.',
            ingredients: 'Espresso, Vanilleeis³⁷, Schlagsahne⁷, Eiswürfel.',
            allergens: '³ Eier · ⁷ Milch/Laktose',
            price: '5,90 €',
          },
          {
            id: 'eislatte',
            name: 'Eislatte',
            description: 'Espresso mit kalter Milch und Eiswürfeln.',
            ingredients: 'Espresso, Milch⁷ oder Hafermilch¹, Eiswürfel.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '5,90 €',
          },
          {
            id: 'eis-karamell-macchiato',
            name: 'Eis-Karamell-Macchiato',
            description: 'Eiskalter Macchiato mit hausgemachtem Karamellsirup.',
            ingredients: 'Espresso, Milch⁷ oder Hafermilch¹, Karamellsirup, Eiswürfel.',
            allergens: '⁷ Milch/¹ Gluten (je nach Wahl)',
            price: '5,90 €',
            badge: 'Beliebt',
            badgeType: 'gold',
          },
          {
            id: 'eisschokolade',
            name: 'Eisschokolade',
            description: 'Kalte Schokolade mit Vanilleeis und Sahne.',
            ingredients: 'Schokolade, Milch⁷, Vanilleeis³⁷, Schlagsahne⁷, Eiswürfel.',
            allergens: '³ Eier · ⁷ Milch/Laktose',
            price: '5,90 €',
          },
        ],
      },

      /* ── Tee & Eistee ── */
      {
        id: 'tee',
        label: 'Heißer Tee & Kalter Eistee',
        items: [
          {
            id: 'schwarzer-tee',
            name: 'Schwarzer Tee',
            description: 'Kräftiger schwarzer Tee, frisch gebrüht.',
            ingredients: 'Schwarztee.',
            allergens: 'Keine bekannten Allergene.',
            price: '3,00 €',
          },
          {
            id: 'gruener-tee',
            name: 'Grüner Tee',
            description: 'Milder grüner Tee, schonend aufgebrüht.',
            ingredients: 'Grüntee.',
            allergens: 'Keine bekannten Allergene.',
            price: '3,00 €',
          },
          {
            id: 'pfefferminz-tee',
            name: 'Pfefferminztee',
            description: 'Frischer Pfefferminztee, belebend und aromatisch.',
            ingredients: 'Pfefferminzblätter.',
            allergens: 'Keine bekannten Allergene.',
            price: '3,00 €',
          },
          {
            id: 'kamillentee',
            name: 'Kamillentee',
            description: 'Beruhigender Kamillentee.',
            ingredients: 'Kamillenblüten.',
            allergens: 'Keine bekannten Allergene.',
            price: '3,00 €',
          },
          {
            id: 'ingwer-zitrone-tee',
            name: 'Ingwer-Zitrone',
            description: 'Wärmender Ingwer mit Zitrone — erfrischend und belebend.',
            ingredients: 'Frischer Ingwer, Zitronensaft, Honig.',
            allergens: 'Keine bekannten Allergene.',
            price: '3,30 €',
          },
          {
            id: 'eistee-mango-rosmarin',
            name: 'Mango Rosmarin Eistee',
            description: 'Hausgemachter Eistee mit Mango und frischem Rosmarin.',
            ingredients: 'Schwarztee, Mangosaft, frischer Rosmarin, Zitrone, Eiswürfel.',
            allergens: 'Keine bekannten Allergene.',
            price: '4,95 €',
            badge: 'Beliebt',
            badgeType: 'gold',
          },
          {
            id: 'eistee-blaubeere-granatapfel',
            name: 'Blaubeere Granatapfel Eistee',
            description: 'Fruchtig-säuerlicher Eistee mit Blaubeere und Granatapfel.',
            ingredients: 'Früchtetee, Blaubeersaft, Granatapfelsaft, Eiswürfel.',
            allergens: 'Keine bekannten Allergene.',
            price: '4,95 €',
          },
          {
            id: 'eistee-brombeer-mandarine',
            name: 'Brombeer Mandarine Eistee',
            description: 'Exotischer Eistee mit Brombeer und Mandarine.',
            ingredients: 'Früchtetee, Brombeersaft, Mandarinensaft, Minze, Eiswürfel.',
            allergens: 'Keine bekannten Allergene.',
            price: '4,95 €',
          },
        ],
      },

      /* ── Alkoholfreie Getränke ── */
      {
        id: 'alkoholfrei',
        label: 'Alkoholfreie Getränke',
        items: [
          {
            id: 'cola',
            name: 'Cola / Fanta / Spezi',
            description: 'Klassische Softdrinks, 0,3 l.',
            ingredients: 'Cola, Fanta oder Spezi.',
            allergens: 'Keine bekannten Hauptallergene.',
            price: '3,20 €',
          },
          {
            id: 'hausgemachte-limonade',
            name: 'Hausgemachte Limonade',
            description: 'Tagesfrisch: Zitrone-Minze, Erdbeere-Basilikum oder Himbeere-Ingwer.',
            ingredients: 'Frische Früchte, Kräuter, Zitronensaft, Zucker, Sodawasser.',
            allergens: 'Keine bekannten Allergene.',
            price: '4,95 €',
            badge: 'Hausgemacht',
            badgeType: 'green',
          },
          {
            id: 'orangensaft',
            name: 'Frisch gepresster Orangensaft',
            description: 'Täglich frisch gepresst, ohne Zusätze.',
            ingredients: 'Frische Orangen.',
            allergens: 'Keine bekannten Allergene.',
            price: '4,80 €',
          },
          {
            id: 'apfelsaft',
            name: 'Apfelsaft / Apfelschorle',
            description: 'Naturtrüber Apfelsaft aus der Region.',
            ingredients: 'Apfelsaft (regional), ggf. Mineralwasser.',
            allergens: 'Keine bekannten Allergene.',
            price: '3,20 €',
          },
          {
            id: 'wasser',
            name: 'Mineralwasser',
            description: 'Still oder mit Kohlensäure, 0,5 l.',
            ingredients: 'Mineralwasser.',
            allergens: 'Keine bekannten Allergene.',
            price: '2,80 €',
          },
        ],
      },

      /* ── Alkoholische Getränke ── */
      {
        id: 'alkoholisch',
        label: 'Alkoholische Getränke',
        items: [
          {
            id: 'merlot',
            name: 'Merlot',
            description: 'Vollmundiger Rotwein mit Noten von Kirschen und Gewürzen.',
            ingredients: 'Rotwein (Merlot). Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 € / Glas',
          },
          {
            id: 'chardonnay',
            name: 'Chardonnay',
            description: 'Eleganter Weißwein mit Pfirsich- und Butteraromen.',
            ingredients: 'Weißwein (Chardonnay). Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 € / Glas',
          },
          {
            id: 'rose',
            name: 'Provence Rosé',
            description: 'Trockener Rosé aus der Provence — sommerlich und frisch.',
            ingredients: 'Roséwein. Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 € / Glas',
          },
          {
            id: 'prosecco',
            name: 'Prosecco DOC',
            description: 'Perlend, frisch, leicht — perfekt für jeden Anlass.',
            ingredients: 'Prosecco DOC (Glera). Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 €',
          },
          {
            id: 'aperol-spritz',
            name: 'Aperol Spritz',
            description: 'Aperol, Prosecco und Soda — der Klassiker.',
            ingredients: 'Aperol (6 cl), Prosecco DOC (9 cl), Soda (3 cl), Orangenscheibe, Eis.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 €',
            badge: 'Beliebt',
            badgeType: 'gold',
          },
          {
            id: 'lillet-spritz',
            name: 'Lillet Spritz',
            description: 'Lillet Blanc, Tonic und frische Früchte.',
            ingredients: 'Lillet Blanc (6 cl), Tonic Water, frische Beeren, Eis.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 €',
          },
          {
            id: 'hugo',
            name: 'Hugo',
            description: 'Prosecco, Holunderblütensirup, Minze und Limette.',
            ingredients: 'Prosecco, Holunderblütensirup, Minze, Limette, Eis.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '5,90 €',
          },
          {
            id: 'moet-chandon',
            name: 'Moët & Chandon',
            description: 'Champagner der Premiumklasse — für besondere Momente.',
            ingredients: 'Champagner (Pinot Noir, Chardonnay, Pinot Meunier). Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '12,50 € / Glas',
            badge: 'Premium',
            badgeType: 'gold',
          },
          {
            id: 'veuve-clicquot',
            name: 'Veuve Clicquot',
            description: 'Eleganter Champagner mit kraftvoller Frucht.',
            ingredients: 'Champagner (Veuve Clicquot Brut). Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: '14,50 € / Glas',
            badge: 'Premium',
            badgeType: 'gold',
          },
          {
            id: 'dom-perignon',
            name: 'Dom Pérignon',
            description: 'Prestige-Cuvée — auf Anfrage.',
            ingredients: 'Champagner (Dom Pérignon Vintage). Enthält Sulfite.',
            allergens: 'Enthält Alkohol & Sulfite.',
            price: 'Auf Anfrage',
            badge: 'Premium',
            badgeType: 'gold',
          },
        ],
      },
    ],
  },
]
